name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 1.0.0-pre.1
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.7.4"

dependencies:
  flutter:
    sdk: flutter
  # Plugin for parsing html
  html: ^0.15.0

  # Plugins for parsing css
  csslib: ^0.17.0
  css_colors: ^1.1.0

  # Plugins for rendering the <video> tag.
  video_player: ^2.0.2
  chewie: ^1.0.0

  # Plugin for rendering the <iframe> tag.
  #webview_flutter: ^0.3.17
  # webview_media: ^0.1.2
  # Plugins for rendering the <audio> tag.
  chewie_audio: ^1.2.0

  # Plugins for rendering the <svg> tag.
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_youtube_view: ^2.0.0
  cached_network_image: ^3.0.0-nullsafety
  webview_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
